### ISSUE TITLE
Infos auch im Artikelbaum

### ISSUE THREAD

**Issue by rustykowski** [e-spin/page-info-bundle#1]
Hallo zonky,
ließe sich die Funktionalität auch auf den Artikelbaum erweitern?
Dort wäre z.B. die Anzeige von CSS-IDs hilfreich, wenn man Skiplinks anlegen möchte.

**Comment by zonky2** [comment]
muss ich mal gucken - sollte eigentlich gehen...

**Comment by e-spin** [comment]
In Version 2 dabei

**Comment by rustykowski** [comment]
Klasse, vielen Dank zonky!
